 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_management_system;
import javax.swing.JRootPane;
import javax.swing.jRootOption;
/**
 *
 * @author M Faisal
 */
public class StudentsReportCard extends javax.swing.JFrame {

    /**
     * Creates new form StudentsReportCard
     */
    public StudentsReportCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mathNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        engNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        urNum = new javax.swing.JTextField();
        islNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gkNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sumbitResultBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Student Results");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Subjects:");

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 153));
        jLabel3.setText("Mathmathicall");

        mathNum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mathNum.setCaretColor(new java.awt.Color(153, 153, 255));
        mathNum.setDisabledTextColor(new java.awt.Color(255, 255, 204));
        mathNum.setSelectedTextColor(new java.awt.Color(204, 255, 204));
        mathNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathNumActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("English");

        engNum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        engNum.setCaretColor(new java.awt.Color(153, 153, 255));
        engNum.setDisabledTextColor(new java.awt.Color(255, 255, 204));
        engNum.setSelectedTextColor(new java.awt.Color(204, 255, 204));
        engNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engNumActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 153));
        jLabel5.setText("Urdu");

        urNum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        urNum.setCaretColor(new java.awt.Color(153, 153, 255));
        urNum.setDisabledTextColor(new java.awt.Color(255, 255, 204));
        urNum.setSelectedTextColor(new java.awt.Color(204, 255, 204));
        urNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urNumActionPerformed(evt);
            }
        });

        islNum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        islNum.setCaretColor(new java.awt.Color(153, 153, 255));
        islNum.setDisabledTextColor(new java.awt.Color(255, 255, 204));
        islNum.setSelectedTextColor(new java.awt.Color(204, 255, 204));
        islNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                islNumActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 153));
        jLabel6.setText("Islamiyat");

        gkNum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gkNum.setCaretColor(new java.awt.Color(153, 153, 255));
        gkNum.setDisabledTextColor(new java.awt.Color(255, 255, 204));
        gkNum.setSelectedTextColor(new java.awt.Color(204, 255, 204));
        gkNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gkNumActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 153));
        jLabel7.setText("Gernal Knowledge");

        sumbitResultBtn.setBackground(new java.awt.Color(0, 255, 204));
        sumbitResultBtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        sumbitResultBtn.setForeground(new java.awt.Color(0, 153, 255));
        sumbitResultBtn.setText("Submit Result");
        sumbitResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumbitResultBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 410, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(53, 53, 53))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sumbitResultBtn)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(urNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(engNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mathNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(islNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gkNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(473, 473, 473))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mathNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(engNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(urNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(islNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(gkNum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(sumbitResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mathNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathNumActionPerformed

    private void engNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engNumActionPerformed

    private void urNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urNumActionPerformed

    private void islNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_islNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_islNumActionPerformed

    private void gkNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gkNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gkNumActionPerformed

    private void sumbitResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumbitResultBtnActionPerformed
        // TODO add your handling code here:
        
        int mat= Integer.parseInt(mathNum.getText());
        int eng= Integer.parseInt(engNum.getText());
        int ur= Integer.parseInt(urNum.getText());
        int isl= Integer.parseInt(islNum.getText());
        int xgk= Integer.parseInt(gkNum.getText());
            int totalMarks = mat + eng + ur + isl + xgk ;
            jOptionPane.showMessageDialog(rootPane, "Total Marks 500 out of" + totalMarks);
    }//GEN-LAST:event_sumbitResultBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsReportCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsReportCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsReportCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsReportCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentsReportCard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField engNum;
    private javax.swing.JTextField gkNum;
    private javax.swing.JTextField islNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mathNum;
    private javax.swing.JButton sumbitResultBtn;
    private javax.swing.JTextField urNum;
    // End of variables declaration//GEN-END:variables

    private static class jOptionPane {

        private static void showMessageDialog(JRootPane rootPane, String string) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public jOptionPane() {
        }
    }

   
}
